apiVersion: v1
data:
  appsettings.json: |
    {
        "KafkaConnection": {
          "BootstrapServers": [ "kafka:9092/" ],
          "ClientId": "audit-events",
          "GroupId": "audit-events"
        },
        "MongoDB": {
          "ConnectionString": "mongodb://link-mongo:VGAbmwOpHiJwAem34Q4yKRn5HWignmc4ylWijGhRUH3gausvb7dyq3254NgoiKnsrjVwwcOvy5RkpD7jWpP11Q==@link-mongo.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@link-mongo@",
          "DatabaseName": "botw-audit",
          "CollectionName": "auditEvents"
        },
        "TelemetryConfig": {
          "TraceExporterEndpoint": "http://localhost:4317/",
          "MetricsEndpoint": "http://localhost:9101", 
          "TelemetryCollectorEndpoint": "http://localhost:55690"
        },
        "AllowReflection": true,
        "EnableSwagger": true,
        "Logging": {
          "LogLevel": {
            "Default": "Information",
            "Microsoft.AspNetCore": "Warning"
          }
        },
        "AllowedHosts": "*",
        "Serilog": {
          "Using": [
            "Serilog.Sinks.Grafana.Loki"
          ],
          "MinimumLevel": {
            "Default": "Information"
          },
          "WriteTo": [
            {
              "Name": "GrafanaLoki",
              "Args": {
                "uri": "http://loki:3100",
                "labels": [
                  {
                    "key": "app",
                    "value": "Link"
                  },
                  {
                    "key": "component",
                    "value": "Audit"
                  }
                ],
                "propertiesAsLabels": [
                  "app",
                  "component"
                ]
              }
            },
            {
              "Name": "Console",
              "Args": {
                "labels": [
                  {
                    "key": "app",
                    "value": "Link-BoTW"
                  },
                  {
                    "key": "component",
                    "value": "Audit"
                  }
                ],
                "propertiesAsLabels": [
                  "app",
                  "component"
                ]
              }
            }
          ]
        }
      }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"appsettings.json":"{\n    \"KafkaConnection\": {\n      \"BootstrapServers\": [ \"kafka:9092/\" ],\n      \"ClientId\": \"audit-events\",\n      \"GroupId\": \"audit-events\"\n    },\n    \"MongoDB\": {\n      \"ConnectionString\": \"mongodb://link-mongo:VGAbmwOpHiJwAem34Q4yKRn5HWignmc4ylWijGhRUH3gausvb7dyq3254NgoiKnsrjVwwcOvy5RkpD7jWpP11Q==@link-mongo.mongo.cosmos.azure.com:10255/?ssl=true\u0026replicaSet=globaldb\u0026retrywrites=false\u0026maxIdleTimeMS=120000\u0026appName=@link-mongo@\",\n      \"DatabaseName\": \"botw-audit\",\n      \"CollectionName\": \"auditEvents\"\n    },\n    \"AllowReflection\": true,\n    \"Logging\": {\n      \"LogLevel\": {\n        \"Default\": \"Information\",\n        \"Microsoft.AspNetCore\": \"Warning\"\n      }\n    },\n    \"AllowedHosts\": \"*\",\n    \"Serilog\": {\n      \"Using\": [\n        \"Serilog.Sinks.Grafana.Loki\"\n      ],\n      \"MinimumLevel\": {\n        \"Default\": \"Information\"\n      },\n      \"WriteTo\": [\n        {\n          \"Name\": \"GrafanaLoki\",\n          \"Args\": {\n            \"uri\": \"http://loki:3100\",\n            \"labels\": [\n              {\n                \"key\": \"app\",\n                \"value\": \"Link\"\n              },\n              {\n                \"key\": \"component\",\n                \"value\": \"Audit\"\n              }\n            ],\n            \"propertiesAsLabels\": [\n              \"app\",\n              \"component\"\n            ]\n          }\n        },\n        {\n          \"Name\": \"Console\"\n        }\n      ]\n    }\n  }\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"audit-config","namespace":"dev-scale"}}
  creationTimestamp: "2023-06-08T19:34:57Z"
  name: audit-config
  namespace: dev-scale
  resourceVersion: "210163599"
  uid: a16eb1d9-8cd3-465f-851c-0ff2ed6f5b6b
