apiVersion: v1
data:
  appsettings.json: |
    {
      "KafkaConnection": {
        "BootstrapServers": ["kafka:9092/"],
        "ClientId": "notification",
        "GroupId": "notification"
      },
      "MongoDB": {
        "ConnectionString": "mongodb://link-mongo:VGAbmwOpHiJwAem34Q4yKRn5HWignmc4ylWijGhRUH3gausvb7dyq3254NgoiKnsrjVwwcOvy5RkpD7jWpP11Q==@link-mongo.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@link-mongo@",
        "DatabaseName": "botw-notification",
        "CollectionName": "Notifications"
      },
      "SmtpConnection": {
        "Host": "lantanagroup-com.mail.protection.outlook.com",
        "Port": 587,
        "EmailFrom": "no-reply@nhsnlink.org",
        "Username": "support@lantanagroup.com",
        "Password": "Copier!Trifle7!Overjoyed"
      },
      "Channels": {
        "IncludeTestMessage": true,
        "TestMessage": "[!** This is a TEST notification, please disregard **!]",
        "SubjectTestMessage": "[!** TEST Notification **!]",
        "Email": true
      },
      "TelemetryConfig": {
        "TraceExporterEndpoint": "http://localhost:4317/",
        "MetricsEndpoint": "http://localhost:9101",
        "TelemetryCollectorEndpoint": "http://localhost:55690"
      },
      "AllowReflection": true,
      "EnableSwagger": true,
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Serilog": {
        "Using": [
          "Serilog.Sinks.Grafana.Loki"
        ],
        "MinimumLevel": {
          "Default": "Information"
        },
        "WriteTo": [{
            "Name": "GrafanaLoki",
            "Args": {
              "labels": [{
                  "key": "app",
                  "value": "Link"
                },
                {
                  "key": "component",
                  "value": "Notification"
                }
              ],
              "propertiesAsLabels": [
                "app",
                "component"
              ]
            }
          },
          {
            "Name": "Console",
            "Args": {
              "labels": [
                {
                  "key": "app",
                  "value": "Link-BoTW"
                },
                {
                  "key": "component",
                  "value": "Notification"
                }
              ],
              "propertiesAsLabels": [
                "app",
                "component"
              ]
            }
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"appsettings.json":"{\n  \"KafkaConnection\": {\n    \"BootstrapServers\": [\"kafka:9092/\"],\n    \"ClientId\": \"notification\",\n    \"GroupId\": \"notification\"\n  },\n  \"MongoDB\": {\n    \"ConnectionString\": \"mongodb://link-mongo:VGAbmwOpHiJwAem34Q4yKRn5HWignmc4ylWijGhRUH3gausvb7dyq3254NgoiKnsrjVwwcOvy5RkpD7jWpP11Q==@link-mongo.mongo.cosmos.azure.com:10255/?ssl=true\u0026replicaSet=globaldb\u0026retrywrites=false\u0026maxIdleTimeMS=120000\u0026appName=@link-mongo@\",\n    \"DatabaseName\": \"botw-notification\",\n    \"CollectionName\": \"Notifications\"\n  },\n  \"SmtpConnection\": {\n    \"Host\": \"lantanagroup-com.mail.protection.outlook.com\",\n    \"Port\": 587,\n    \"EmailFrom\": \"no-reply@nhsnlink.org\",\n    \"Username\": \"support@lantanagroup.com\",\n    \"Password\": \"Copier!Trifle7!Overjoyed\"\n  },\n  \"Channels\": {\n    \"IncludeTestMessage\": true,\n    \"TestMessage\": \"[!** This is a TEST notification, please disregard **!]\",\n    \"SubjectTestMessage\": \"[!** TEST Notification **!]\",\n    \"Email\": true\n  },\n  \"AllowReflection\": true,\n  \"Logging\": {\n    \"LogLevel\": {\n      \"Default\": \"Information\",\n      \"Microsoft.AspNetCore\": \"Warning\"\n    }\n  },\n  \"AllowedHosts\": \"*\",\n  \"Serilog\": {\n    \"Using\": [\n      \"Serilog.Sinks.Grafana.Loki\"\n    ],\n    \"MinimumLevel\": {\n      \"Default\": \"Information\"\n    },\n    \"WriteTo\": [{\n        \"Name\": \"GrafanaLoki\",\n        \"Args\": {\n          \"labels\": [{\n              \"key\": \"app\",\n              \"value\": \"Link\"\n            },\n            {\n              \"key\": \"component\",\n              \"value\": \"Notification\"\n            }\n          ],\n          \"propertiesAsLabels\": [\n            \"app\",\n            \"component\"\n          ]\n        }\n      },\n      {\n        \"Name\": \"Console\"\n      }\n    ]\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"notification-config","namespace":"dev-scale"}}
  creationTimestamp: "2023-06-08T19:35:06Z"
  name: notification-config
  namespace: dev-scale
  resourceVersion: "211704730"
  uid: 3f369098-d1f8-4b24-8f9a-3e24a55a539a
