apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo
  jsonData:
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: Loki
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        #query: 'TraceID="${__span.tags.method}"'
        query: '{app="{Link-BoTW}"} |= `` | json | TraceId = `${__span.tags.traceId}`'
      tracesToMetrics:
        datasourceUid: Prometheus
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(process_runtime_dotnet_gc_committed_memory_size_bytes{$__tags}[5m]))'
      serviceMap:
        datasourceUid: Prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: Loki
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      spanBar:
        type: 'Tag'
        tag: 'http.path'
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  apiVersion: 1
  uid: loki
  jsonData:
    maxLines: 1000
    derivedFields:
      # Field with internal link pointing to data source in Grafana.
      # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
      # datasourceUid value can be anything, but it should be unique across all defined data source uids.
      - datasourceUid: Tempo
        matcherRegex: .*TraceId\":"(\w{32}).*
        name: TraceID
        # url will be interpreted as query for the datasource
        url: '$${__value.raw}'


      