receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw
  batch:

exporters:
  otlp/tempo:
    endpoint: tempo:4417
    tls:
      insecure: true
  otlp/jeager:    
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint:  collector:9464

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, otlp/jeager]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]