global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: 'collector'
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
    - targets: ['collector:9464']