trigger:
  branches:
    include:
    - LNK-1913-Update-Audit-service-to-Dot-NET8
  paths:
    include:
    - Audit/*
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Link_BOTW_Build_Package_Variables
- name: project
  value: 'Audit/Audit.csproj'
- name: testProject
  value: 'AuditUnitTests/AuditUnitTests.csproj'
- name: nugetPath
  value: 'Audit/nuget.config'
- name: tags1
  value: 'dotnet8'
- name: tags2
  value: '$(Build.BuildId)'
- name: registry-repo-Name
  value: 'aca-audit:dotnet8'
- name: dockerPath
  value: '**/Audit/Dockerfile'
steps:
  - task: PowerShell@2
    displayName: 'Transform nuget.config'
    inputs:
      targetType: 'inline'
      script: |
        $path = '$(System.DefaultWorkingDirectory)/Audit/nuget.config'
        $nugetUrl = '$(nuget)'
        $sharedUrl = '$(Shared_BOTW_Feed)'
        $token = '$(System.AccessToken)'
        $basePath = '$(System.DefaultWorkingDirectory)'
        
        $xml = [xml](Get-Content -Path $path)
        
        $node = $xml.configuration.packageSources.add |
                where { $_.key -eq 'nuget' }
        $node.value = $nugetUrl
        
        Write-Host "updated nuget url:"
        Write-Host $node.value
        
        $node = $xml.configuration.packageSources.add |
                where { $_.key -eq 'Shared_BOTW_Feed' }
        $node.value = $sharedUrl
        
        Write-Host "Shared botw url:"
        Write-Host $node.value
        
        $node = $xml.configuration.packageSourceCredentials.Shared_BOTW_Feed.add |
                where { $_.key -eq 'ClearTextPassword' }
        $node.value = $token
        
        Write-Host "updated token:"
        Write-Host $node.value
        
        $xml.Save($path)

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)'
    displayName: 'Run Tests'
  

  - task: Docker@2
    displayName: "Build & Push Audit Docker Image"
    condition: always()
    inputs:
      containerRegistry: 'Link ACR'
      repository: $(registry-repo-name)
      command: 'buildAndPush'
      Dockerfile: $(dockerPath)
      tags: |
        $(tags1)
        $(tags2)
      buildContext: '$(Build.Repository.LocalPath)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'manifest'
