server:
  port: 5135

spring:
  application:
    name: measureeval

  data:
    mongodb:
      database: ${spring.application.name}

  kafka:
    consumer:
      group-id: ${spring.application.name}

    producer:
      client-id: ${spring.application.name}
