logging:
  level:
    com.lantanagroup.link: debug

server:
  port: 5135

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

secretManagement:
  managerUri: https://link-vault.vault.azure.net/

authentication:
  enableAnonymousAccess: true

spring:
  application:
    name: measureeval

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.application.name}

  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
      default-view-inclusion: false

  kafka:
    bootstrap-servers:
      - localhost:9092

    consumer:
      group-id: ${spring.application.name}

    producer:
      client-id: ${spring.application.name}

link:
  reportability-predicate: com.lantanagroup.link.measureeval.reportability.IsInInitialPopulation

  data-acquisition:
    base-url: http://localhost:5194
    routes:
      query-result:
        path: /api/{facilityId}/QueryResult/{correlationId}
        query:
          - queryType={queryType}
