server:
  port: 5135

spring:
  application:
    name: measureeval

  data:
    mongodb:
      database: ${spring.application.name}

  jackson:
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
      default-view-inclusion: false

  kafka:
    consumer:
      group-id: ${spring.application.name}

    producer:
      client-id: ${spring.application.name}

link:
  data-acquisition:
    base-url: http://localhost:5194
    routes:
      query-result: /api/{facilityId}/QueryResult/{patientId}
