trigger:
  paths:
    include:
    - DotNet/PatientsToQuery/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/PatientsToQuery/PatientsToQuery.csproj'
  testProject: 'DotNet/PatientsToQueryUnitTests/PatientsToQueryUnitTests.csproj'
  serviceName: 'PatientsToQuery'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

