trigger:
  paths:
    include:
    - DotNet/DemoApiGateway/*

name: Demo API Gateway CI

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Link_BOTW_Build_Package_Variables
- name: project
  value: 'DotNet/DemoApiGateway/DemoApiGateway.csproj'
- name: nugetPath
  value: 'DotNet/DemoApiGateway/nuget.config'
- name: serviceName
  value: 'DemoApiGateway'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
      verbosityRestore: Diagnostic
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'



