trigger:
  paths:
    include:
    - DotNet/Notification/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/Notification/Notification.csproj'
  testProject: 'DotNet/NotificationUnitTests/NotificationUnitTests.csproj'
  nugetPath: 'DotNet/Notification/nuget.config'
  serviceName: 'Notification'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

