trigger:
  paths:
    include:
    - Validation/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'Validation/Validation.csproj'
  testProject: 'ValidationUnitTests/ValidationUnitTests.csproj'
  nugetPath: 'Validation/nuget.config'
  serviceName: 'Validation'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

