trigger:
  paths:
    include:
    - DotNet/QueryDispatch/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/QueryDispatch/QueryDispatch.csproj'
  testProject: 'DotNet/QueryDispatchUnitTests/QueryDispatchUnitTests.csproj'
  serviceName: 'QueryDispatch'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

