trigger:
  paths:
    include:
    - DemoApp/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: RaulARuiz.angular-cli-1.angular-cli-build-task.AngularCLI@1
    displayName: 'ng build'
    inputs:
      project: DemoApp
      prod: false

