trigger:
  paths:
    include:
    - DotNet/MeasureEval/*
    - DotNet/Shared/*
    
pr:
  paths:
    include:
    - DotNet/MeasureEval/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/MeasureEval/MeasureEval.csproj'
  testProject: 'DotNet/MeasureEvalUnitTests/MeasureEvalUnitTests.csproj'
  serviceName: 'MeasureEval'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

