trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - DotNet/QueryDispatch/*
    - DotNet/Shared/*
    exclude:
    - '*'
    
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Link_BOTW_Build_Package_Variables
- name: project
  value: 'DotNet/QueryDispatch/QueryDispatch.csproj'
- name: testProject
  value: 'DotNet/QueryDispatchUnitTests/QueryDispatchUnitTests.csproj'
- name: tags1
  value: 'latest'
- name: tags2
  value: '$(Build.BuildId)'
- name: registry-repo-Name
  value: 'link-querydispatch'
- name: dockerPath
  value: '**/DotNet/QueryDispatch/Dockerfile'
- name: serviceName
  value: 'QueryDispatch'
- name: containerRegistry
  value: 'NHSNLink ACR Premium'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)'
    displayName: 'Run Tests'
  

  - task: Docker@2
    displayName: "Build & Push QueryDispatch Docker Image"
    condition: always()
    inputs:
      containerRegistry: $(containerRegistry)
      repository: $(registry-repo-name)
      command: 'buildAndPush'
      Dockerfile: $(dockerPath)
      tags: |
        $(tags1)
        $(tags2)
      buildContext: '$(Build.Repository.LocalPath)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'manifest'
