trigger:
  paths:
    include:
    - DotNet/Audit/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/Audit/Audit.csproj'
  testProject: 'DotNet/AuditUnitTests/AuditUnitTests.csproj'
  nugetPath: 'DotNet/Audit/nuget.config'
  serviceName: 'Audit'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
      verbosityRestore: Diagnostic
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

