trigger:
  paths:
    include:
    - Java/validation/*

pool:
  vmImage: 'ubuntu-latest'
  
variables:
- group: Link_BOTW_Build_Package_Variables

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@2
    displayName: Maven Install
    inputs:
      mavenPomFile: 'Java/pom.xml'
      goals: install
      options: '-pl validation -am'