trigger:
  paths:
    include:
    - Audit/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Link_BOTW_Build_Package_Variables
- name: project
  value: 'Audit/Audit.csproj'
- name: testProject
  value: 'AuditUnitTests/AuditUnitTests.csproj'
- name: nugetPath
  value: 'Audit/nuget.config'
- name: tags1
  value: 'latest'
- name: tags2
  value: '$(Build.BuildId)'
- name: registry-repo-Name
  value: 'link-audit'
- name: dockerPath
  value: '**/Audit/Dockerfile'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

