trigger:
  paths:
    include:
    - DotNet/PatientList/*
    - DotNet/Shared/*
    
pr:
  paths:
    include:
    - DotNet/PatientList/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'DotNet/PatientList/PatientList.csproj'
  testProject: 'DotNet/PatientListUnitTests/PatientListUnitTests.csproj'
  nugetPath: 'DotNet/PatientList/nuget.config'
  serviceName: 'PatientList'

steps:
  - template: ../azure-nuget-package-source.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      nugetConfigPath: '$(nugetPath)'
      feedsToUse: config
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)
    displayName: 'Run Tests'

