trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - DotNet/Audit/*
    - DotNet/Shared/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Link_BOTW_Build_Package_Variables
- name: project
  value: 'DotNet/Audit/Audit.csproj'
- name: testProject
  value: 'DotNet/AuditUnitTests/AuditUnitTests.csproj'
- name: registry-repo-name
  value: 'link-audit'
- name: dockerPath
  value: '**/DotNet/Audit/Dockerfile'
- name: serviceName
  value: 'Audit'  
- name: containerRegistry
- name: containerRegistryUrl

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(testProject)'
    displayName: 'Run Tests'
  
  - task: Docker@2
    displayName: "Build & Push Audit Docker Image"
    condition: always()
    inputs:
      containerRegistry: $(containerRegistry)
      repository: $(registry-repo-name)
      command: 'buildAndPush'
      Dockerfile: $(dockerPath)
      arguments: '--cache-from=$(containerRegistryUrl)/$(registry-repo-name):latest'
      tags: |
        $(Build.BuildId)
        latest
      buildContext: '$(Build.Repository.LocalPath)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'manifest'
