trigger:
  paths:
    include:
    - DotNet/DemoApiGateway/*
    - DotNet/Shared/*
    
pr:
  paths:
    include:
    - DotNet/DemoApiGateway/*
    - DotNet/Shared/*

name: Demo API Gateway CI

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Link_BOTW_Build_Package_Variables
- name: project
  value: 'DotNet/DemoApiGateway/DemoApiGateway.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(project)'
      verbosityRestore: Diagnostic
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'



