artifact:
  init: true
loki:
  enabled: false
  url: ''
server:
  port: 31820

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


spring:
  application:
    name: ValidationService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ''
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=true;database=link-dev-botw-validation;user=sa;password=Temp123;trustServerCertificate=true
  jpa:
    properties:
      show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
      jakarta:
        persistence:
          schema-generation.scripts.action: create
          schema-generation.scripts.create-target: src/main/resources/db/schema.sql
          schema-generation.create-source: metadata
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: validation
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      client-id: validation-service
    #properties:
      #security.protocol: SASL_SSL
      #sasl.mechanism: PLAIN
      #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="";

secret-management:
  key-vault-uri: ''

authentication:
  anonymous: false
  authority: ''
